### ISSUE TITLE
jenks: off by one?

### ISSUE THREAD

**Issue by FragLegs** [simple-statistics/simple-statistics#101]
On line 984, you have `kclass[countNum - 1] = data[lower_class_limits[k][countNum] - 1];`

However, in geostats, line 855 is `var id = parseInt((mat1[k][countNum]) - 2)`
In the Java implementation, they use `int id =  (int) (mat1[k][j]) - 2;`
and in the python implementation on line 50 they use `id = int((mat1[k][countNum]) - 2)`

Is this a typo? From your blog post, you say you have the original paper. Is your -1 in keeping with Jenks' original algorithm?

**Comment by tmcw** [comment]
Superseded by https://github.com/simple-statistics/simple-statistics/issues/117
