### ISSUE TITLE
getting `NaN` on simple linear regression

### ISSUE THREAD

**Issue by chriddyp** [simple-statistics/simple-statistics#112]
just starting out with `simple-statistics`:

```
> ss = require('simple-statistics')
> lg = ss.linear_regression([[0, 0], [1, 0]])
> lg.mb()
{'m': NaN, 'b': NaN}
```

not sure if my usage is right here or not. Thanks for the help!

**Comment by phoeagon** [comment]
You are not on the latest branch and are therefore looking for incorrect examples.
On the version you work on, it should be:

      > lg = ss.linear_regression().data([[0, 0], [1, 0]]).mb()

which should give the correct result.
Alternatively, and preferably, upgrade to our latest version and:

      > ss.linearRegression([[0,0],[1,0]])
      { m: 0, b: 0 }

**Comment by tmcw** [comment]
:+1: yep, just what @phoeagon said - the `master` branch contains what will be 1.0.0, and will have the

```
 > ss.linearRegression([[0,0],[1,0]])
  { m: 0, b: 0 }
```

Behavior that separates the line function generation and the intercept/slope generation.
