### ISSUE TITLE
Reimplement Jenks

### ISSUE THREAD

**Issue by tmcw** [simple-statistics/simple-statistics#117]
> http://journal.r-project.org/archive/2011-2/RJournal_2011-2_Wang+Song.pdf

This approach to Jenks is simpler and faster than our existing approach. I'm planning on a clean-room implementation of the stated algorithm as a full replacement for v1.0.0.

**Comment by stuaxo** [comment]
Since you are doing a clean room implementation, it might be worth considering using numpy.

**Comment by tmcw** [comment]
This is a JavaScript library, and numpy is in Python.

**Comment by stuaxo** [comment]
Doh, sorry for the noise - have been looking at python libraries for the last few years :)

**Comment by tmcw** [comment]
In JavaScript-land, a fast implementation might use [ndarray](https://github.com/scijs/ndarray), but the intent of simple-statistics is to be understandable first, so this implementation will start with normal ol' arrays.

**Comment by tmcw** [comment]
Success! https://github.com/simple-statistics/simple-statistics/pull/118
