### ISSUE TITLE
Derive chi-squared table

### ISSUE THREAD

**Issue by tmcw** [simple-statistics/simple-statistics#121]
What @mourner did with the [standard normal table](https://github.com/simple-statistics/simple-statistics/pull/108) was awesome - deriving the table makes simple-statistics smaller and makes the table more explanatory. The chi-squared table is still hardcoded - we should figure out how to derive it as well.

**Comment by mourner** [comment]
Looking at the description, this is pretty difficult, derived from the incomplete gamma function, code for which alone will probably take more space than the table here.

**Comment by tmcw** [comment]
Good point - we'll keep the table for now.
