### ISSUE TITLE
New NPM release needed

### ISSUE THREAD

**Issue by stevage** [simple-statistics/simple-statistics#129]
```
ss.ckmeans([1,2,2,2,3,4,5,99],5)
=> [ [ 1, 2 ], [ 2, 2 ], [ 3, 4 ], [ 5 ], [ 99 ] ]
```

I'm not sure if I'm misunderstanding how `ckmeans` should operate, but this behaviour seems very odd to me. I don't really get how a value (`2`) can be in multiple clusters. Visually, this would mean one region with a value of `2` is represented with a different colour from two other regions with the value `2`. That can't be right?

It also seems problematic in terms of using this function: how would I decide which `2` goes into which cluster?

Am I simply not understanding right, or is there actually a problem here?

Exploring further, it really feels like a bug:

```
ss.ckmeans([1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,5],3)
[ [ 1, 2 ],
  [ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 ],
  [ 5 ] ]
```

**Comment by stevage** [comment]
OIC, this is already known at https://github.com/simple-statistics/simple-statistics/issues/124, which is still open. (The "I fixed it" is referring to a python implementation...)

**Comment by stevage** [comment]
Actually...it's merged, but there hasn't been a new NPM release. Master behaves right:

```
s.ckmeans([1,2,2,2,3,4,5,99],5)
[ [ 1 ], [ 2, 2, 2 ], [ 3, 4 ], [ 5 ], [ 99 ] ]
```

It still returns multiple clusters per value if you ask for more clusters than the number of unique values:

```
> ss.ckmeans([1,2,2,2,3,4,5,99],8)
[ [ 1 ], [ 2 ], [ 2 ], [ 2 ], [ 3 ], [ 4 ], [ 5 ], [ 99 ] ]
```

But I don't know what the expected behaviour is there. At least it's not grouping different values in one cluster, while separating repeated values.

**Comment by tmcw** [comment]
:+1: Cut a new release: [v1.0.1](https://github.com/simple-statistics/simple-statistics/releases/tag/v1.0.1)

**Comment by stevage** [comment]
Thanks!
