### ISSUE TITLE
ckmeans doesn't like NaN

### ISSUE THREAD

**Issue by Fil** [simple-statistics/simple-statistics#131]
```
JSON.stringify(ss.ckmeans([1,2,3, 1, 2, 3,NaN], 2))
"[[null,1,1,2,2,3],[3]]"
```

should we add `.filter(function(d){ return !isNaN(d); })` or `.map(function(d){ return +d; })` in the code, or in the docs, maybe?

**Comment by tmcw** [comment]
I think filtering out invalid values should be in your code: the ckmeans algorithm has no special treatment for null or nan values, and the documentation specifies that input should be an array of numbers.

**Comment by brylie** [comment]
Would it be reasonable for `ss.ckmeans` to [type-check the data input](https://github.com/simple-statistics/simple-statistics/blob/master/src/ckmeans.js#L67 and throw an error if the data type is not an array?

**Comment by tmcw** [comment]
Implementing validation of all inputs would incur a performance hit on all functions: runtime checks for invalid input shouldn't be in simple-statistics. `v1.1.0` will include Flow types (#133) which will provide up-front checking with no runtime performance hit.
