### ISSUE TITLE
Linear Regression exampled linked in README is broken

### ISSUE THREAD

**Issue by jseppi** [simple-statistics/simple-statistics#138]
Looks like you just have an incorrect path to `simple_statistics.js` in your gist. It should be `https://rawgit.com/tmcw/simple-statistics/master/dist/simple_statistics.js`.

@shawnbot actually found the issue previously: https://gist.github.com/tmcw/3931800#gistcomment-1491602

**Comment by tmcw** [comment]
👍 Thanks for bringing this up. Now adopting a more robust way of doing this: http://bl.ocks.org/tmcw/3931800/972696d92e86c4f541ec0c89b5657771b40e99fa

Dist files are now included in npm builds and accessible through npmcdn.
