### ISSUE TITLE
Link to Wiki/documentation broken

### ISSUE THREAD

**Issue by harishnavnit** [simple-statistics/simple-statistics#148]
The [Moved to API.md](https://github.com/simple-statistics/simple-statistics/blob/master/API.md) text on in the [Wiki section](https://github.com/simple-statistics/simple-statistics/wiki) leads to a 404 !

**Comment by brylie** [comment]
I changed the link so that it points to the main API docs. Does this resolve the issue?

**Comment by harishnavnit** [comment]
Yes, it does. Thanks :+1:

**Comment by tmcw** [comment]
Thanks for the help @brylie !
