### ISSUE TITLE
[Help] Linear Regression examples

### ISSUE THREAD

**Issue by harishnavnit** [simple-statistics/simple-statistics#149]
I know there's an [example on Linear Regression](http://bl.ocks.org/tmcw/3931800) but that is done by including D3 libraries to draw the plots etc. 
My requirement is to create simple plots/lines using linear regression on a mapbox project using the leafletjs API. 
I don't think there's a need to include the D3 libraries et. all for this purpose. There must be an easier way out. All I need is to display a line on the map, which can be achieved by using Polylines. I'm just not sure how the values returned by the `linearRegression()` or `linearRegressionLine()` functions can be used for this purpose. 

Any help would be much appreciated.

**Comment by brylie** [comment]
Do you have a code example? What format is the data, lat/long?

**Comment by harishnavnit** [comment]
Yes, the data format is lat/long. Is it required to convert data to cartesian form before applying the `linearRegression*` functions ? If yes, that would mean converting the cartesian points back to geodetic coordinates, which I don't think is straightforward, is it ?

Here's the [code](https://github.com/harishnavnit/noc) and this is how my plot on the map looks right now. 
![screenshot_20160609_130627](https://cloud.githubusercontent.com/assets/5815030/15922133/d0f108e0-2e43-11e6-9787-bb174506708d.png)
Is it because I'm using lat/long input data or is it a flawed logic on my side ?
The yellow line is my attempt at plotting the output of the `linearRegressionLine()` function and the markers on the red line are the input data. 

The following files are relevant, 
1. [app.js](https://github.com/harishnavnit/NOC/blob/master/app.js)
2. [map.js](https://github.com/harishnavnit/NOC/blob/master/src/js/map.js)
3. [path.js](https://github.com/harishnavnit/NOC/blob/master/src/js/path.js)

**Comment by brylie** [comment]
One thing might be to check if your coordinates cross the prime meridian.

**Comment by harishnavnit** [comment]
So, passing lat/long data as input to the functions are not an issue, right ?

**Comment by harishnavnit** [comment]
And how does checking if coordinates cross the prime meridian help ? I don't know of the logic behind that.

**Comment by brylie** [comment]
Ah, I was thinking of the possibility of coordinates crossing from 180 to -180.

**Comment by brylie** [comment]
Would you please provide an example array of geographic coordinates? Lets isolate this issue a bit.

**Comment by brylie** [comment]
OK, I did some experimentation. It seems like the regression line code needs several steps. Here is my work-in-progress:

```js
var ss = require("simple-statistics");

var coordinates = [
    [61.508122,23.746948],
    [60.984933,24.472046],
    [60.191889,24.927979]
];

coordinates;

var regression = ss.linearRegression(coordinates);

var regressionLine = ss.linearRegressionLine(regression);

var regressionStart = regressionLine(coordinates[0][0]);
var regressionEnd = regressionLine(coordinates[2][0]);

regressionStart;
regressionEnd;
```

**Comment by harishnavnit** [comment]
Oh cool, did you get a chance to test how the line looks on a map ?
Here's an example array of geographic coordinates : http://dpaste.com/3QRK3R2

**Comment by brylie** [comment]
I am still workin g on the process. I think I am on the right path, or line :-)

**Comment by harishnavnit** [comment]
@brylie oh that's great. I just happened to edit my previous comment FYI.

**Comment by brylie** [comment]
OK, here is my working code:

```js
var ss = require("simple-statistics");

var coordinates = [
    [61.508122,23.746948], // Tampere, Finland
    [60.984933,24.472046], // Hämeenlinna, Finland
    [60.191889,24.927979] // Helsinki, Finland
];

coordinates;

var regression = ss.linearRegression(coordinates);

var regressionFunction = ss.linearRegressionLine(regression);

// Set up starting and ending X coordinates
var regressionStartX = coordinates[0][0];
var regressionEndX = coordinates[2][0];

// Calculate starting and ending Y coordinates
var regressionStartY = regressionFunction(regressionStartX);
var regressionEndY = regressionFunction(regressionEndX);

var regressionLine = [
    [regressionStartX, regressionStartY],
    [regressionEndX, regressionEndY]
];


regressionLine;
```

You can try it out by pasting it in the [NPM simple-statistics package sandbox](https://tonicdev.com/npm/simple-statistics). Then, click **Run** and select **Map coordinates list** in the dropdown box next to the `Array` output.

**Comment by brylie** [comment]
Does that seem to work as expected?

**Comment by harishnavnit** [comment]
Wow. That does look legit. I'm just gonna check on my map for sanity. I now realize that you only had to pass the start and end points of the regression line. I was iterating over all the points in the coordinate list and that obviously wasn't helping the cause :-)

**Comment by harishnavnit** [comment]
@brylie it works perfectly ! Thank you so much for your help :-) :+1: :100: 
![screenshot_20160609_145724](https://cloud.githubusercontent.com/assets/5815030/15924964/ab578690-2e52-11e6-8464-f4f22e8bdb61.png)

**Comment by brylie** [comment]
You're welcome :-) One more thing though, what happens if a shipping route goes from, say, Tokyo to Los Angeles? I am concerned how the linear regression might perform when crossing the international date line, or 180 to -180.

**Comment by harishnavnit** [comment]
I honestly haven't thought about that because I only had the southern coast of India in mind. Let's see how your algo works in that case. Posting the screenshot soon.

**Comment by brylie** [comment]
OK, cool.

**Comment by harishnavnit** [comment]
@brylie hmm, your concerns seem to have come true. 
![screenshot_20160609_151400](https://cloud.githubusercontent.com/assets/5815030/15925484/f62d47a2-2e54-11e6-860f-b864ffec2782.png)

Also worth noting that I'm drawing these lines for every 5th marker that's created on the map. `if (no_of_markers % 5 == 0) { drawRegressionLine() }` or something like that.

**Comment by brylie** [comment]
Well there might be a geospatial processing/analysis library that is better equipped to handle the international date line issue. E.g. [Turf.js](http://turfjs.org/) seems promising.

**Comment by harishnavnit** [comment]
Thanks! There are still a few more things on the TODO (eg: these lat/long inputs should come from a remote device - android phone for eg) and I'm working on that as well. I'll take a look at Turf.js as soon as other things are sorted out :)

**Comment by brylie** [comment]
Cool. Neat project :-)
