### ISSUE TITLE
Consider switching to faster Ckmeans implementation

### ISSUE THREAD

**Issue by schnerd** [simple-statistics/simple-statistics#157]
It looks like Ckmeans support was added to simple-statistics by @tmcw in August 2015 as a part of #124. On May 25th, 2016 the original authors of the Ckmeans algorithm [released a new version](https://cran.r-project.org/web/packages/Ckmeans.1d.dp/NEWS) (3.4.6) that significantly increased to the performance of the core algorithm. The improvement is described in their [package overview](https://cran.r-project.org/web/packages/Ckmeans.1d.dp/Ckmeans.1d.dp.pdf), here's an excerpt of the relevant portion:

>A major speed-up has been introduced since version 3.4.6 using a divide-and-conquer strategy in dynamic programming. The runtime is reduced from O(kn^2) down to O(kn lg n), log-linear in
sample size n. This method is numerically stable and observed runtime is often close to linear in
practice. These improvements, not discussed in (Wang and Song, 2011), will be described in detail in a future publication.

Based on my inspection of the simple-statistics ckmeans implementation as well as performance tests, it definitely appears to be getting close to O(kn^2) runtime. Having an O(kn lg n) javascript implementation would be a major win. I wanted to open this issue to hear your thoughts on whether this improvement has already been discovered/discussed, and if you think it would make a good addition to simple-statistics.

**Comment by tmcw** [comment]
Absolutely, the Ckmeans implementation in simple-statistics would definitely benefit from a faster algorithm, and if it's numerically stable, all the better. Is this something you'd be interested in porting to JS?

**Comment by schnerd** [comment]
Glad to hear there's interest! I'm traveling over the next two weeks but I can probably take a stab at porting the code over when I return to the states. Will keep you updated!

**Comment by schnerd** [comment]
Quick update–successfully ported the code and can confirm major speed improvements. I'm going to clean it up a bit more and open a PR.

**Comment by schnerd** [comment]
Pull request open #163

**Comment by tmcw** [comment]
Implemented in #163 - thanks @schnerd !
