### ISSUE TITLE
Add "ss." in documentation.

### ISSUE THREAD

**Issue by fega** [simple-statistics/simple-statistics#170]
Hello, I was trying to using the library following the docs, but I never see the namespace "ss." in it, it was strange, but it is never mentioned until you see the examples.

Please consider add this to the documentation.

**Comment by tmcw** [comment]
Thanks for noting that, @fega! I'll add a notice about this to the documentation, saying that if you use the `<script>` tag version of simple-statistics, the methods are available under `ss`. When you include simple-statistics in node.js or browserify, you choose the name methods are grouped by.
