### ISSUE TITLE
Linear time mean & variance updates

### ISSUE THREAD

**Issue by Yomguithereal** [simple-statistics/simple-statistics#178]
Hello `simple-statistics`. Would you consider it a useful addition (that I can make through a PR) to have functions updating means and variances in constant time? Things such as:

* `addToMean`
* `substractFromMean`
* `combineMeans`
* `combineVariances`

Because the addition of some values to a sequence shouldn't force the user to recompute the mean or variance again in linear time in some use cases.

What do you think?

**Comment by tmcw** [comment]
Absolutely! These would be a great addition. I'm also working on stream-statistics, which I'm [improving in v2](https://github.com/simple-statistics/stream-statistics/pull/12), and does entirely online statistics. Would be great to have a literate implementation of the update methods in simple-statistics too, as a reference point.

**Comment by Yomguithereal** [comment]
Ok, I'll wrap a PR when I can then :)

**Comment by Yomguithereal** [comment]
PR were done and merged. Closing.
