### ISSUE TITLE
Make it faster (master ticket)

### ISSUE THREAD

**Issue by tmcw** [simple-statistics/simple-statistics#194]
![](https://media.tenor.co/images/83daa77b58d29d51e0b090dceeef7c96/tenor.gif)

In 3.0.0, I introduced [benchmarks](https://github.com/simple-statistics/simple-statistics/tree/master/benchmarks), so I now know how simple-statistics compares to other modules! Yay! And it 'wins' in some cases, but loses in others! Boo. I've done 30 solid minutes of digging here and can braindump a few results.

## Low-hanging fruit ✅ #195

`sumNthPowerDeviations` is internally called with n=2 and n=3. `Math.pow(x, 2)` is significantly slower than `x * x`: by swapping one for other, we'll get a quick win on sampleVariance:

```
global.ss.sampleVariance x 7,604,134 ops/sec ±0.81% (90 runs sampled)
global.ssMaster.sampleVariance x 9,283,292 ops/sec ±0.48% (92 runs sampled)
```

This is a bummer, since it isn't as 'literate' and makes the code slightly less similar to the written math algorithm, but alas, that's where we're at.

## Source of ambiguity

simple-statistics uses [Kahan summation](https://en.wikipedia.org/wiki/Kahan_summation_algorithm) by default, which is great since it's error-correcting and leads to more accurate sums and means. Unfortunately, it means extra work: it's slower than a normal sum, and since every other statistics library uses a simple sum algorithm instead, that's a performance hit.

I lean toward keeping Kahan summation as long as possible, but rethinking this decision sporadically.

## Design question

simple-statistics uses functions-calling functions so that algorithms can reuse each other: for instance, [sampleSkewness](https://github.com/simple-statistics/simple-statistics/blob/cfd98ade353336e2470015f0e6380ff7e22512ec/src/sample_skewness.js#L23-L36) uses sumNthPowerDeviations and sampleStandardDeviation under the hood. This is great for readability, but it is wasting some processor time, since, in that case, the call tree looks like:

* sampleSkewness
  * sumNthPowerDeviations (n=3)
    * **mean**
      * sum
  * sampleStandardDeviation
    * sampleVariance
      * sumNthPowerDeviations (n=2)
        * **mean**
          * sum

So, as you can see, we're computing **mean** twice. Now, mean is `O(n)`, but as I mentioned earlier, we're using Kahan sums, so it's a little more expensive than it might otherwise be, plus it feels _wrong_ as wasted work.

I can see a few solutions to this problem:

* A hidden parameter to certain methods that lets internal methods pass through pre-computed means. Or, if we don't want to be sneaky, a non-exported method that takes mean as an argument and can be used internally.
* We could store `.__mean` on the array itself and check for it before re-computing it.

## Bluesky performance: asm?

[asm.js](http://asmjs.org/spec/latest/) is [a bit controversial](http://mrale.ph/blog/2013/03/28/why-asmjs-bothers-me.html) and has spotty browser support, but it's very interesting for simple-statistics because it's so well-directed at exactly the problems we'd want to solve.

The question for me here is whether supporting asm.js would give enough performance boost for it to be worth the time, and whether it'd be significantly different in code style or whether we could kind of 'blend' it in. I'll keep considering this one but it isn't on the top of my list.

**Comment by Yomguithereal** [comment]
Concerning Kahan summation, I guess it would be possible to "activate" it only when detecting the first float of the given sequence, else it's pointless. But testing for float might be more costly than the actual computations required by Kahan's correction.

**Comment by mourner** [comment]
We should address algorithmical inefficiencies first and foremost — e.g. recomputed mean (I vote for non-exported utility). Better algorithm is the reason we're beating everyone at median/quantile. 

For a fair benchmark, 1000-item input is too small. I'd find a single run on a 100,000-item array much more reliable than a benchmark.js loop on a 1000-item.

**Comment by tmcw** [comment]
It's very fast now.

![image](https://user-images.githubusercontent.com/32314/50541973-34af8a80-0b66-11e9-8e5c-bba3a843da61.png)
