### ISSUE TITLE
Speeding up variance

### ISSUE THREAD

**Issue by Yomguithereal** [simple-statistics/simple-statistics#202]
It's possible to compute variance in only one pass (currently, variance is computed using two passes, one to compute the sum and hence the mean, and a second one to compute the sum of squared deviations).

The idea is to perform a single loop where you'll compute:

1. The sum of xi `sum`.
2. The sum of squared xi `sumSq`.

The variance is then `sumSq - ((sum * sum) / n) / n`

This method is known to have bad edge cases fixed by another method presented [here](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance) (the Welford's method).

Refs #194.

**Comment by Yomguithereal** [comment]
Note that with those methods it's also possible to return both mean & variance in one pass.

**Comment by mourner** [comment]
Sounds good! Although Wikipedia mentions that Welford may be slower than two-pass due to division in each iteration. Let's try it out and benchmark.

**Comment by Yomguithereal** [comment]
Just tried to benchmark Welford's method and it seems it's running at 1/3 of the speed of the two-pass method. So I guess we can close this :).

**Comment by Yomguithereal** [comment]
Will close this now. @mourner I'll let you re-open if you need to.
