### ISSUE TITLE
Use ES6 modules + Rollup

### ISSUE THREAD

**Issue by mourner** [simple-statistics/simple-statistics#210]
As the front-end world rapidly moves to ES6-compatible bundling, simple-statistics could really benefit from switching from CommonJS to ES6 modules and Rollup. It may introduce small additional set up for tests and NPM prepublish scripts, but advantages now overweight the cons IMO. The library will especially benefit from tree-shaking (also see #180), leaner browser builds, and being future-proof.

SS would still have a CommonJS-compatible entry point for Node, but additionally use `pkg.module` for ES6-aware consumers. The Webpack code splitting issues should not hold us back because they're not ES6-specific, and are probably still a problem when you try to set up code splitting with CommonJS modules. 

Examples of other libraries that switched happily to Rollup include React, Vue, Ember, Preact, D3, Three.js, Moment and PouchDB.

cc @tmcw @Yomguithereal

**Comment by tmcw** [comment]
My opinion here: yep, let's do it. The time has come for ES6 modules, and this'll also let us switch out of Flow comment syntax ( https://github.com/documentationjs/documentation/issues/729 ) and use prettier.

**Comment by tmcw** [comment]
I'm reconsidering: getting tests, with code coverage, leaves you with a lot fewer options than in ES5, and size is not a top concern of simple-statistics. We'd most likely have to drop node-tap, or include a convoluted babel setup, and occasionally run into babel and rollup's different implementations of ES6 modules.

I'm totally +1 on ES6 modules (iD, Studio, .com, and others use them) but for such a small and simple library, the overhead feels like it outweighs the benefit.

**Comment by mourner** [comment]
@tmcw check this out, maybe it'll help: https://medium.com/web-on-the-edge/es-modules-in-node-today-32cff914e4b

**Comment by tmcw** [comment]
😍 wat how is that even possible... I'm going to have to read the guts of that module

**Comment by DenisCarriere** [comment]
@mourner I also believe using [`@std/esm`](https://github.com/standard-things/esm) is the way to go. It will be an easy win without any fallbacks.

@tmcw You want me to send a PR with an implementation of this? The `simple-statistics` library is much easier to implement the ES6 export/import syntax than [`converting TurfJS to ES6 import/exporty code`](https://github.com/Turfjs/turf/pull/960/files).

**Comment by DenisCarriere** [comment]
Implemented ES6 modules using only Rollup, `@std/esm` wasn't necessary (Rollup bundles are so fast, 1.5s for entire bundling process including uglifying)
