### ISSUE TITLE
Make it more obvious in the docs that the main object is 'ss'

### ISSUE THREAD

**Issue by kyle-sorensen** [simple-statistics/simple-statistics#227]
Tiny little sentence in your entire docs says this.

**Comment by tmcw** [comment]
Hi Kyle,

Do you have a suggestion of what would be more informative? The current style is:

![2017-06-22 at 10 01 am](https://user-images.githubusercontent.com/32314/27446278-d4808ffe-5731-11e7-903c-f3dd44f28d56.png)

My impression is that this is pretty clear and prominent, but I'm open to other style suggestions.

**Comment by kevinmcdonald19** [comment]
In my node.js app, I had to 'require' the 'simple-statistics' module.  should i not have to do this normally?  if so, it'd be helpful adding to the docs.

`const ss = require('simple-statistics');
`

**Comment by tmcw** [comment]
Yep, @kevinmcdonald19 - that's the normal way to require modules when you're using node.js. The name `ss` is only a default when you use simple-statistics via a script tag in a browser. In node, you always get to choose what name (variable binding) is attached to the modules you import.

I'll try improving the readme to make this clearer!

**Comment by tmcw** [comment]
What do y'all think of this for a section in the readme that tries to make it clearer how to require & use the module? https://gist.github.com/tmcw/39467b5b68988a9e3e265a072def8be8

**Comment by Yomguithereal** [comment]
I guess we cannot get clearer than that. The one more thing we could do is provide a link to the build of the library in the tag case but that's it.

**Comment by Fil** [comment]
A related issue: the documentation is about `perceptronModel` but the function is [exported](https://github.com/simple-statistics/simple-statistics/blob/master/index.js#L69) as `ss.perceptron` — you have to look it up in the code or in the `ss` object keys to find it.

**Comment by tmcw** [comment]
Hm, indeed - I'll open a separate issue for that. PerceptronModel should be exported as PerceptronModel (all classes should be capitalized). Might be a proper case to export both and then deprecate in the next major version.

**Comment by Fil** [comment]
Same with `ss.bayesian => BayesianClassifier` while we're at it — I have checked all the others.
