### ISSUE TITLE
Kernel density estimation

### ISSUE THREAD

**Issue by anandthakker** [simple-statistics/simple-statistics#244]
[Kernel density estimation](https://en.wikipedia.org/wiki/Kernel_density_estimation) is a useful tool for (among other things) estimating the shape of the underlying probability distribution from a sample.  @tmcw would you be interested in / open to a PR adding KDE functionality?  Something like:

```js
kde: (x: Array<number>, kernel: KernelFunction, bandwidth: number) => DensityFunction
```

`KernelFunction` is a `number => number` that's non-negative and integrates to 1.

The hard part of using KDE (for non-experts like me, anyway) is the selection of the kernel and bandwidth -- indeed, that's much harder than the implementation of `kde` itself -- so I think the real value of having something like this in `simple-statistics` would be in providing good defaults for those:
 - [R](https://www.rdocumentation.org/packages/stats/versions/3.4.1/topics/bandwidth) defaults to a Gaussian kernel and uses what appears to be a common/traditional [rule-of-thumb bandwidth](https://en.wikipedia.org/wiki/Kernel_density_estimation#A_rule-of-thumb_bandwidth_estimator) choice.
 - [Haskell's `Statistics.Sample.KernelDensity`](https://hackage.haskell.org/package/statistics-0.14.0.2/docs/Statistics-Sample-KernelDensity.html) uses a different method, from [this paper by Botev, et al](https://arxiv.org/pdf/1011.2602.pdf) which the docs claim outperform the above approach.  (Haven't yet read the paper.)

**Comment by anandthakker** [comment]
cc @jfirebaugh

**Comment by tmcw** [comment]
👍 Yep, would definitely be open to a PR! Other prior arts are [scipy, which explicitly calls it 'gaussian kde'](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html), and [science.js, which sets gaussian to the default and lets you customize it](https://github.com/jasondavies/science.js/blob/master/src/stats/kde.js).
