### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by DenisCarriere** [simple-statistics/simple-statistics#247]
👍 / 👎  for a built-in Typescript definition?

This will be very easy to include since the Flow Types are already defined and tons of JSDocs.

It would simply be a single file `index.d.ts` that looks like this:

```typescript
export function addToMean(mean: number, n: number, newValue: number): number;
export function bernoulliDistribution(p: number): number[];
export function binomialDistribution(trials: number, probability: number): number[] | undefined;
```

Pretty easy for someone to send PR's with fixes or new methods.

CC: @tmcw

**Comment by tmcw** [comment]
Totally! simple-statistics is very straightforward with its method signatures, not much polymorphism here :)

**Comment by DenisCarriere** [comment]
👍 Implemented via PR: https://github.com/simple-statistics/simple-statistics/pull/255
