### ISSUE TITLE
Jenks zero index?

### ISSUE THREAD

**Issue by stuaxo** [simple-statistics/simple-statistics#25]
Question - in the bits looping over the arrays I notice item 1 is set and all the loops go to len + 1.

Is this a side effect of fortran arrays starting at 1 ?

On a quick look, it looks like the zeroth elements are only accessed when the matrices are cleared.

http://developeronline.blogspot.co.uk/2008/04/why-array-index-should-start-from-0.html

This is probably just me misunderstanding the maths though :)

**Comment by tmcw** [comment]
Superseded by https://github.com/simple-statistics/simple-statistics/issues/117
