### ISSUE TITLE
Implement lowess

### ISSUE THREAD

**Issue by tmcw** [simple-statistics/simple-statistics#30]
http://en.wikipedia.org/wiki/Local_regression

**Comment by tmcw** [comment]
Could never find a pseudocode or proof for loess - it's apparently an approach, not a specific implementation.

**Comment by brylie** [comment]
If it might be helpful, we did some initial research about  LOEWW/LOWESS implementations for MetricsGraphics:

- https://github.com/mozilla/metrics-graphics/issues/540

It may be possible to find a proof or citation from one of the existing implementations.

**Comment by brylie** [comment]
One reference for a LOWESS implementation comes from William S. Cleveland:

- [Locally Weighted Regression: An Approach to Regression Analysis by Local
Fitting](http://www.stat.washington.edu/courses/stat527/s13/readings/Cleveland_Delvin_JASA_1988.pdf)

**Comment by brylie** [comment]
Also, the following article might be useful:

- [Nonparametric Regression:  Lowess/Loess](http://www.ime.unicamp.br/~dias/loess.pdf) adapted by Ronaldo Dias
