### ISSUE TITLE
Switch to TypeScript

### ISSUE THREAD

**Issue by tmcw** [simple-statistics/simple-statistics#313]
I'm pretty pessimistic about Flow vs TS going forward. This shouldn't matter much for the external API surface of simple-statistics, because we aren't really exposing a Flow-annotated version anyway, and we're already exposing TS defs.

**Comment by Yomguithereal** [comment]
I agree with you.

**Comment by tmcw** [comment]
I changed my mind; I don't think this project really needs types that badly, and I still don't like the TS ecosystem.
