### ISSUE TITLE
Bundling issue for standalone script case

### ISSUE THREAD

**Issue by ThomasG77** [simple-statistics/simple-statistics#324]
When I add just the unminified standalone script in a minimum html file

    <script src='https://unpkg.com/simple-statistics@6.1.0/dist/simple-statistics.js' />

it returned the following error
```
Uncaught ReferenceError: exports is not defined
    at <anonymous>:3:23
```
Due to this behavior, the namespace `ss` is not initialized and something like `ss.linearRegression` fails whereas typing `linearRegression` in the console works but does not seems the right way of working if I compare it with the documentation in the `README.md` that state the following

> When you use simple-statistics from a script tag, you don't get to choose the variable name it is assigned to: simple-statistics will always become available globally as the variable ss. You can reassign this variable to another name if you want to, but doing so is optional.

Can you confirm?

I also tried with

    <script src='https://unpkg.com/simple-statistics@6.1.0/dist/simple-statistics.min.js' />

and it works FIY

**Comment by tmcw** [comment]
Ah, yes - I need to update the documentation so it only recommends using the `.min.js` version with a script tag.
