### ISSUE TITLE
RangeError: Invalid string length when length of array is long

### ISSUE THREAD

**Issue by Jaszkowic** [simple-statistics/simple-statistics#330]
I have an array `xs` with > 29000 entries. When calculating `Stat.sum(xs)` (or other statistics) i get the following error:

> (node:43568) UnhandledPromiseRejectionWarning: RangeError: Invalid string length

For comparison i tried jStat, which did not throw the error leaving everything else unchanged. Maybe there is some problem with memory allocation?

**Comment by Yomguithereal** [comment]
Can you provide a minimal reproducible example of your issue so we can try and pinpoint where the bugs comes from please? By `xs` do you mean [this](https://github.com/staltz/xstream) library?

**Comment by Jaszkowic** [comment]
I will try to provide a minimal example. `xs` is just the name of my array variable in plain javascript.
