### ISSUE TITLE
Fix Microbundle configuration

### ISSUE THREAD

**Issue by mourner** [simple-statistics/simple-statistics#347]
From [this comment](https://github.com/simple-statistics/simple-statistics/issues/333#issuecomment-450410716):

> It appears that this fix is not included in the current browser build. It looks like microbundle was introduced at the same time this was released, which seems relevant. I've verified that the fix is included in `dist/simple-statistics.js`, but not in `dist/simple-statistics.min.js` for v6.1.1. Also, `dist/simple-statistics.js` is now minified, which was not the case for v6.1.0. Hopefully this information is helpful. Please let me know if I can provide more information, or if there's anything I can do to help.

Edit: we should also address #344 at the same time.

**Comment by tmcw** [comment]
Thanks for moving the comment to an issue

There's a long and drawn out discussion about the compression-by-default at https://github.com/developit/microbundle/issues/66 - that part I don't classify as a bug. If it changes upstream, sure, I'll update microbundle, but as it stands I don't think that a compressed main entry constitutes a breaking change or is necessarily a bad default. If there's a discussion about that, I think it belongs upstream in microbundle.

Fixed the flipped umd:main entry in https://github.com/simple-statistics/simple-statistics/pull/351 and released 7.0.0
