### ISSUE TITLE
"Uncompressed development" link is compressed

### ISSUE THREAD

**Issue by bennlich** [simple-statistics/simple-statistics#394]
I guess this is related to or maybe a duplicate of https://github.com/simple-statistics/simple-statistics/issues/347

My personal preference would be to offer an uncompressed version for download. To me this feels most in the spirit of "Statistical methods in readable JavaScript for browsers, servers, and people."

Alternatively, keep it compressed, and change the link label on the home page :-P

Thanks for making this lib! I'm excited to use it.

**Comment by tmcw** [comment]
That's right, and I should fix it. I've opened #396 and am working through some issues with the CI tests and then will have a release with an unminified build.

**Comment by tmcw** [comment]
Released 7.0.6 with a fixed non-compressed entry point.

**Comment by bennlich** [comment]
🙌
