### ISSUE TITLE
version 7.0.6 not compile es2015 by babel

### ISSUE THREAD

**Issue by imsobear** [simple-statistics/simple-statistics#406]
![image](https://user-images.githubusercontent.com/2505411/69024659-b4ed1180-09fe-11ea-8da8-f29032ad3e5c.png)

![image](https://user-images.githubusercontent.com/2505411/69024646-aa327c80-09fe-11ea-9077-4d52d1bfb0fd.png)

![image](https://user-images.githubusercontent.com/2505411/69024668-c2a29700-09fe-11ea-9ea1-f8d161303959.png)

**Comment by tmcw** [comment]
That's right, my bad. Although I think I we should stop transpiling soon because the only engines without `let` support are ancient, it'll be in a major version.

**Comment by tmcw** [comment]
Transpiled code restored in 7.0.7.
