### ISSUE TITLE
Uncaught ReferenceError: tTestTwoSample is not defined

### ISSUE THREAD

**Issue by interhealth** [simple-statistics/simple-statistics#441]
in a browser app, I am trying to call tTestTwoSample as described in the Doc
html:
<script type="text/javascript" src="https://unpkg.com/simple-statistics@7.0.8/dist/simple-statistics.min.js"></script>

js:
tTestTwoSample([1, 2, 3, 4], [3, 4, 5, 6], 0); 

Console:
"Uncaught ReferenceError: tTestTwoSample is not defined"

does simple-statistics need to be instantiated / initialized somehow?

**Comment by tmcw** [comment]
If you're using simple statistics with a script tag, you'll need to refer to functions with the `ss.` prefix, like

```js
ss.tTestTwoSample([1, 2, 3, 4], [3, 4, 5, 6], 0);
```

**Comment by interhealth** [comment]
Thank you, Tom.
Found the solution here: https://stackoverflow.com/questions/43042889/typescript-referenceerror-exports-is-not-defined

add this before all the JS

<script>var exports = {};</script>
