### ISSUE TITLE
Error in linearRegresson

### ISSUE THREAD

**Issue by mcclella** [simple-statistics/simple-statistics#513]
I was using linearRegression in an Observable notebook and getting strange results.  So I tried a test case that produced obviously incorrect results:

ss = require("simple-statistics@7")
line = ss.linearRegression([[1,2,3], [3,2,1]])
line = Object {
  m: 0
  b: 2
}

The correct answer is obviously m: -1   and b: 4

**Comment by tmcw** [comment]
Hi Gary,

linearRegression takes an array of 2-element arrays, as [x, y] pairs. (see [docs](https://simplestatistics.org/docs/#linearregression)). Your example _looks_ like it's trying to use an array per dimension. If you adjust it to use the documented data format,

```
ss.linearRegression([[1, 3], [2, 2], [3, 1]])
```

Gives you your intended result.

**Comment by mcclella** [comment]
oops, my bad.  I haven’t worked with Simple Statistics in a while.  I think I was fooled by emulating the structure of the function call in sampleCorrelation().  Can you delete my issue or should I?

thanks for your quick response and thanks for your work on Simple Statistics.  

gary

gary.mcclelland@mac.com
+1 303.641.3629
