### ISSUE TITLE
Do we have "Coefficient of Variation" function ?

### ISSUE THREAD

**Issue by angelyaaaaa** [simple-statistics/simple-statistics#526]
I've searched within all document and code, it seems there is no function for Coefficient of Variation 
: https://en.wikipedia.org/wiki/Coefficient_of_variation

I assume it will look like this : https://simplestatistics.readthedocs.io/en/latest/index.html?highlight=coefficient%20variation#coefficient-of-variation

I wonder if there is any function I missed ? or this it's in the plan ?

**Comment by tmcw** [comment]
This function isn't currently included. I'm open to including it - it would likely be a one-line method, given that the [python implementation is so tiny](https://simplestatistics.readthedocs.io/en/latest/_modules/simplestatistics/statistics/coefficient_of_variation.html#coefficient_of_variation) in the meantime, if you want to calculate it, it is just standard deviation divided by the mean.

**Comment by angelyaaaaa** [comment]
cool, I'll send a pr

**Comment by tmcw** [comment]
Thanks - merged and released in 7.4.0!
