### ISSUE TITLE
Exports section of the package.json may need to be updated

### ISSUE THREAD

**Issue by jpireaud** [simple-statistics/simple-statistics#527]
I updated my npm packages today and it now requires to have the package.json file explicitly listed in the exports section.

So here is the modified version:

```
"exports": {
    "./package.json": "./package.json",
    "." : {
      "import": "./dist/simple-statistics.mjs",
      "require": "./dist/simple-statistics.js"
    }
  },
```
Hope it will help! Thanks!

**Comment by tmcw** [comment]
Hahaha, wow, okay - thank you for the heads-up. One of these days we'll have a JavaScript packaging spec that lasts longer than a year 😆

**Comment by altearius** [comment]
This issue is affecting me. Would it be helpful if I generate a PR to implement @Huolju 's proposed fix?  I have verified that the suggested fix resolves the problem in my case.

**Comment by tmcw** [comment]
Sure. Fwiw, what tool is already requiring this format, and how is it doing that without breaking… basically every npm module?

**Comment by altearius** [comment]
Thanks, I've submitted a PR for this.

It works on my machine, but of course, please test it on yours!

Without this fix, I found that React Native would issue warnings when using this package.  I do not know why this package gets singled out.  I have 13 other dependencies.  I did a quick sample of about half of them and none that I looked at had an "exports" section in their package.json at all.
