### ISSUE TITLE
Is there a way to efficiently calculate Skewness and Kurtosis of data having value with repetitions ?

### ISSUE THREAD

**Issue by rockfight** [simple-statistics/simple-statistics#542]
The data is for example

Price --> Volume

100 ---> 1234

101 ---> 123456

102 ---> 6678

103 ---> 3456

104 ---> 1115

To calculate it I have to pass an array with '100' 1234 times, '101' 123456 times and so on. This is quite inefficient for large datasets. Is there a general method to calculate it.

**Comment by kgryte** [comment]
@rockfight Use a weighted skewness formula, which would allow you to provide custom weights.
