### ISSUE TITLE
mean() evaluates nulls as zeros in calculation

### ISSUE THREAD

**Issue by jrossner** [simple-statistics/simple-statistics#608]
The mean() function does not raise an error for null values in sample, nor is there a note in the [documentation](https://simplestatistics.org/docs/#mean) specifying this. 

Here's an example of where I realized this:
`
const ss = require("simple-statistics");
`
`
var x = [null, 30, null];
`
`
console.log(ss.mean(x));
`
which returns: 
`
10
`

If the array provided to mean() contains NaNs, strings, or undefined values the mean() returns NaN, which I believe is sufficient. I'm sure the code behind mean() simply uses JS Math on an array and and divides it by the length of the array, but a note somewhere so users know to drop nulls (or return NaN) would be helpful!

**Comment by tmcw** [comment]
True, this issue persists because `null + 1 = 1`. I'll work on a fix.

**Comment by jrossner** [comment]
great! thank you @tmcw
