### ISSUE TITLE
Make simple-statistics available as a deno module?

### ISSUE THREAD

**Issue by dsaxton** [simple-statistics/simple-statistics#622]
@tmcw Looks like there isn't much in the way of high quality statistics modules available in deno right now, so I wonder if it might make sense to publish this one? I don't actually know what's involved in doing that or how difficult it would be, but thought I'd throw the idea out there: https://deno.land/x

**Comment by tmcw** [comment]
Good idea! We're now published to Deno.land: https://deno.land/x/simplestatistics@v7.7.3

**Comment by dsaxton** [comment]
Awesome!

```javascript
import { factorial } from "https://deno.land/x/simplestatistics@v7.7.3/index.js";

console.log(factorial(5));
// 120
```
