### ISSUE TITLE
Explicit type-checking

### ISSUE THREAD

**Issue by dsaxton** [simple-statistics/simple-statistics#625]
It seems a lot of the functions in simple-statistics assume the type of the input is correct which leads to some inconsistent output when it's not. Here are some examples if someone makes the understandable mistake of passing multiple arguments when an array is expected:

```javascript
> min(1, 2, 3)
undefined
> max(1, 2, 3)
undefined
> mean(1, 2, 3)
NaN
> median(1, 2, 3)
Uncaught TypeError: x.slice is not a function
    at quantile (https://deno.land/x/simplestatistics@v7.7.3/src/quantile.js:26:20)
    at median (https://deno.land/x/simplestatistics@v7.7.3/src/median.js:20:13)
    at <anonymous>:2:1
> mode(1, 2, 3)
Uncaught TypeError: x.slice is not a function
    at numericSort (https://deno.land/x/simplestatistics@v7.7.3/src/numeric_sort.js:22:14)
    at mode (https://deno.land/x/simplestatistics@v7.7.3/src/mode.js:25:23)
    at <anonymous>:2:1
```

(Here I'm using the deno module -- thank you for adding that :smile: -- which actually wouldn't compile example code like this, but in the REPL this can still happen. Certainly in node and browser-based code it would as well.)

Would it be useful to do explicit type-checking and raise an error whenever the input is invalid in cases like this?

**Comment by tmcw** [comment]
I'd prefer not to have simple-statistics do type checking. We already provide TypeScript definitions, for those using TypeScript, which would catch this mistake at the compile step. And there's thorough documentation for which types and functions are supported.

Adding type-checking at the simple-statistics level would add complexity and performance cost for all users, but only benefit folks who rely on neither documentation nor typescript. In some cases it might be simple - using Array.isArray to check `mode` input, but should we check every item of the array to confirm that they're all numbers? Fixing this problem in the general case would possibly add quite a lot of both complexity & efficiency cost for too small a benefit.

**Comment by dsaxton** [comment]
Good points, thanks for the explanation @tmcw
