### ISSUE TITLE
Bring back Jenks

### ISSUE THREAD

**Issue by curran** [simple-statistics/simple-statistics#672]
Even though Ckmeans may be superior to Jenks, the Jenks algorithm is of historical interest. It would be great to have a working implementation of Jenks around for reference and use. For me personally, I'm working on a book about data visualization and I'd like to include an example that uses Jenks. The deprecated implementation in this library seems to be the best around.

FWIW I landed here after reading [Literate Jenks Natural Breaks and How The Idea Of Code is Lost](https://macwright.com/2013/02/18/literate-jenks.html) and searching for the source.

It is possible to try Jenks now by using an older build of this library, 0.9.2, but would it be a possibility to bring back Jenks to the official current API? I think the implementation of this change would be fairly trivial, just bringing back the [old files that were removed](https://github.com/simple-statistics/simple-statistics/pull/118/files#diff-b95ab92f03e4150ced5c6fcaa9b82d607aa74a04de21f6b07a12f10a24f56d50)

I'd love to ultimately make something like [ckmeans & now deprecated Jenks Natural Breaks with simple-statistics and d3](http://bl.ocks.org/thadk/37ff4c03358b414acd1e), but without hackery around using older versions.

Is this something you'd be open to? Thanks!

**Comment by tmcw** [comment]
Merged and released in 2.8.0!

**Comment by curran** [comment]
Wow amazing! Thank you so much! Hooray!
