### ISSUE TITLE
add missing TypeScript typing for sampleRankCorrelation

### ISSUE THREAD

**Issue by joaopgsilva** [simple-statistics/simple-statistics#689]
Can the same thing that was done for https://github.com/simple-statistics/simple-statistics/commit/d4ca1590e93a71c625099d21d84ab0230bad9ccc be done for sampleRankCorrelation?

The import seems to be missing on https://github.com/simple-statistics/simple-statistics/blob/main/index.d.ts#L45

**Comment by tmcw** [comment]
Thanks for the heads-up, fixed in #689 and released with 7.8.1.
