### ISSUE TITLE
Documentation is Inaccessible 

### ISSUE THREAD

**Issue by trogers1** [simple-statistics/simple-statistics#720]
The Doc site is not accessible when clicking the `API Documentation` link in the README:

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/b836965a-e252-421e-89ed-19d2a07ac3a7">

**Comment by secretwpn** [comment]
still an issue. to make matters worse now the domain is used by some cybersquatters and shows some potentially questionable content.

look at `linear_regression.d.ts` file for example
```typescript
/**
 * https://simplestatistics.org/docs/#linearregression
 */
declare function linearRegression(data: number[][]): { m: number; b: number };

export default linearRegression;

```
