### ISSUE TITLE
our environement cannot support node 18 ,you shoule change the core back

### ISSUE THREAD

**Issue by TryChai** [simple-statistics/simple-statistics#730]
![27f6c7390bd8b0197a2ac12fbee6aa3](https://github.com/user-attachments/assets/1f32b66a-3c3b-4cb8-81e6-3e98f504efd7)
Are you has many time to do something to harm me ?why do you do that?why do you change the old version without consider ourself?
Maybe you update the code with more cause but you should consider our environment cannot support. My environment cannot supprot  
more than node 18,you must change the core back,and update the code in new version

**Comment by tmcw** [comment]
7.8.5 allows any version of Node. However, your behavior on this issue tracker is wildly out of line with the [code of conduct](https://github.com/simple-statistics/simple-statistics/blob/main/code_of_conduct.md), so I'm blocking you from this repository. Learn some manners.
