### ISSUE TITLE
[commonjs--resolver] Failed to resolve entry for package "simple-statistics". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by zhw2590582** [simple-statistics/simple-statistics#740]
I don't know why there is this error, but it was normal after I locked the @7.8.5 version, I am a `nuxt3` project and use `@visactor/vchart`

![Snipaste_2024-10-16_23-21-30](https://github.com/user-attachments/assets/e624fd73-ff4c-4d89-be8b-6dfc0706d446)

```json
  "resolutions": {
    "simple-statistics": "7.8.5"
  },
```

**Comment by tmcw** [comment]
Weird, it looks like pnpm didn't build the module before pushing it… just pushed 7.8.7 which should fix the issue, can you check?

**Comment by zhw2590582** [comment]
Yes, 7.8.7 is works now
