### ISSUE TITLE
No information in repo about v7.8.7

### ISSUE THREAD

**Issue by gorner** [simple-statistics/simple-statistics#741]
Version 7.8.7 has been published to NPM, however it doesn't appear this is reflected in the GitHub repo's `main` branch and it's not clear what's changed compared to 7.8.6. I'd appreciate some clarification to ensure 7.8.7 was not published unexpectedly.

(Aside: I miss [Package Diff](https://medium.com/intrinsic-blog/introducing-package-diff-for-npm-e6487cc9b434), which I used to be able to use to compare versions in circumstances like this)

**Comment by tmcw** [comment]
Ah, okay - just pushed 7.8.7 as a commit. I'll probably switch to `np` or something because the release workflow for this module isn't that great right now. 7.8.7 has no changes, it was only published because 7.8.6 was a broken release that was missing the `dist/` directory.
