### ISSUE TITLE
question : variance or sample variance? 

### ISSUE THREAD

**Issue by fprivitera** [simple-statistics/simple-statistics#81]
I read your code and I didn't understand what is the difference between variance and sample variance. is it just  the different value of denominator? I would expect that sample variance is a variance calculated on a subset.

Thanks

**Comment by tmcw** [comment]
Thanks for flagging this - I'll make a note to document sample * vs * more thoroughly in the source & docs. [Sample variance](http://en.wikipedia.org/wiki/Variance#Population_variance_and_sample_variance) (and sample mean, sample covariance) are more subtle than subsets - see [wolfram alpha's explanation](http://mathworld.wolfram.com/SampleVariance.html) for a little more.
