### ISSUE TITLE
Low-variance shifted data

### ISSUE THREAD

**Issue by tmcw** [simple-statistics/simple-statistics#83]
Hi, please consider improving the variance calculation to handle low-variance floating point numbers:

https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Computing_shifted_data

From #82

**Comment by plato-cambrian** [comment]
here's what I wrote for my use case:

    function findShiftedVariance(data){
      if(data.length === 0){ 
        throw new Error('Calculating variance of empty array')
      }
      
      var n;
      var K;
      var variance;
      var sum;
      var sumSqr;

      K = prices[0];
      sum = 0;
      sumSqr = 0;
      for(n=0; n<data.length; n++){
        var x = data[n];
        sum = sum + (x - K);
        sumSqr = sumSqr + ((x - K) * (x - K));
      }
      variance = (sumSqr - ( (sum*sum)/n ) ) / n;
      return variance;
    }

**Comment by plato-cambrian** [comment]
hmm re-reading I note that I am dividing by `n` in the last step because I have a complete data set; but if the data set is a sample of a larger data set you should divide by `n-1`. how annoying :D

**Comment by tmcw** [comment]
Happy to accept a PR implementing this feature, but reading more about these algorithms doesn't uncover any that are sufficiently canonical.
